config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  resources :disasters, except: :show

  resources :posts do
    resources :comments, except: :show
  end

  namespace :user do
    resources :posts, only: :index
    resources :comments, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
  validates :content, presence: true
end

app/models/disaster.rb
class Disaster < ApplicationRecord
  validates :name, presence: true

  has_many :post_disaster_ships, dependent: :destroy
  has_many :posts, through: :post_disaster_ships
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :address, presence: true

  has_many :post_disaster_ships, dependent: :destroy
  has_many :disasters, through: :post_disaster_ships
  has_many :comments, dependent: :destroy

  belongs_to :user
  mount_uploader :image, ImageUploader

  scope :ordered_by_comments_count, -> {
    left_joins(:comments)
      .group(:id)
      .order('COUNT(comments.id) DESC')
      .select('posts.*, COUNT(comments.id) as comments_count')
  }
  scope :top_posts, -> { left_joins(:comments).group(:id).order('COUNT(comments.id) DESC').limit(3) }
end

app/models/post_disaster_ship.rb
class PostDisasterShip < ApplicationRecord
  belongs_to :post
  belongs_to :disaster
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = @post.comments
    @comments = @comments.page(params[:page]).per(5)
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to user_comments_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @comment.user = current_user
    if @comment.update(comment_params)
      flash[:notice] = 'Comment updated successfully'
      redirect_to user_comments_path
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = 'Comment deleted successfully'
    redirect_to post_comments_path(@post)
  end

  private

  def set_post
    @post = Post.find params[:post_id]
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/disasters_controller.rb
class DisastersController < ApplicationController
  before_action :set_disaster, only: [:edit, :update, :destroy]

  def index
    @disasters = Disaster.all
  end

  def new
    @disaster = Disaster.new
  end

  def create
    @disaster = Disaster.new(disaster_params)
    if @disaster.save
      flash[:notice] = 'Disaster created successfully'
      redirect_to disasters_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @disaster.update(disaster_params)
      flash[:notice] = 'Disaster Type updated successfully'
      redirect_to disasters_path
    else
      render :edit
    end
  end

  def destroy
    @disaster.destroy
    flash[:notice] = 'Disaster Type deleted successfully'
    redirect_to disasters_path
  end

  private

  def set_disaster
    @disaster = Disaster.find(params[:id])
  end

  def disaster_params
    params.require(:disaster).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to root_path
    else
      flash.now[:alert] = 'Post create failed'
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    @post.user = current_user
    if @post.update(post_params)
      flash[:notice] = 'Post updated successfully'
      redirect_to user_posts_path
    else
      flash.now[:alert] = 'Post update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Post destroyed successfully'
    redirect_to user_posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :address, :image, disaster_ids: [])
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comments = current_user.comments
    @comments = @comments.page(params[:page]).per(5)
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: :destroy

  def index
    @posts = current_user.posts.all.ordered_by_comments_count
    @posts = @posts.page(params[:page]).per(6)
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Post destroyed successfully'
    redirect_to user_posts_path
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @top_posts = Post.top_posts
    @posts = Post.includes(:disasters, :user).all.ordered_by_comments_count
    @posts = @posts.page(params[:page]).per(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disasters_helper.rb
module DisastersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_with model: comment, url: path, data: { turbo: false } do |form| %>
  <% if comment.errors.any? %>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="container2">
    <div class="comments">
      <h3><%= @post.title %>
        <span style="color: blue;"> by </span><span style="color: #5f4c75;"><%= @post.user&.email %></span></h3>
      <div class="form1">
        <%= form.label :comment %>
        <%= form.text_field :content %>
      </div>
      <div class="submit">
        <%= form.submit %>
        <%= link_to 'Cancel', root_path, class: 'btn' %>
      </div>
    </div>
    <div class="back1">
      <%= link_to 'Back', root_path, class: 'btn btn-home', style: 'width:150px;' %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render partial: 'form', locals: { post: @post, comment: @comment, path: post_comment_path(@post, @comment) } %>

app/views/comments/index.html.erb
<div class="container1">
  <div class="comments">
    <h3>Comments <span style="color: white;"><%= @post.comments_count %></span></h3>
    <% @comments.each do |comment| %>
      <div class="comments-border">
        <div class="container-comments">
          <div class="comments1"><%= comment.content %>
            <span style="color: #825991;"> by </span><span style="color: #371f41;"><%= comment.user&.email %></span>
          </div>

          <%= link_to 'Edit', edit_post_comment_path(@post, comment), class: 'btn btn-edit' if user_signed_in? && comment.user == current_user %>
          <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete, class: 'btn' if user_signed_in? && comment.user == current_user %>
        </div>
        <div class="created_at">Created at: <%= comment.created_at %></div>
      </div>
    <% end %>
    <div class="post-container">
      <%= link_to 'Back Home', root_path, class: 'btn btn-home', style: 'width:150px;' %>
      <%= link_to 'Add New Post', new_post_path, class: 'btn btn-success' %>
      <div class="add-comment"><%= link_to 'Add Comment', new_post_comment_path(@post), class: 'btn', style: 'width: 150px;' %></div>
    </div>
  </div>
</div>
<div class="paginate"><%= paginate @comments %></div>

app/views/comments/new.html.erb
<%= render partial: 'form', locals: { post: @post, comment: @comment, path: post_comments_path(@post) } %>

app/views/disasters/_form.html.erb
<%= form_with model: disaster, url: path, data: { turbo: false } do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/disasters/edit.html.erb
<h1>disaster id: <%= @disaster.id %></h1>
<%= render partial: 'form', locals: { disaster: @disaster, path: disaster_path(@disaster) } %>

app/views/disasters/index.html.erb
<h1>Disaster Type</h1>

<ul>
  <% @disasters.each do |disaster| %>
    <li>
      <%= disaster.name %>
      <%= link_to :edit, edit_disaster_path(disaster) %>
      <%= button_to :delete, disaster_path(disaster), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'new', new_disaster_path %>

app/views/disasters/new.html.erb
<h1>New Disaster Type</h1>
<%= render partial: 'form', locals: { disaster: @disaster, path: disasters_path } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  <style>
      .pagination {
          list-style: none;
          display: flex;
          justify-content: center;
      }

      .pagination li {
          margin: 5px 8px;
      }

      .pagination a {
          padding: 5px 10px;
          border: 1px solid #ccc;
          text-decoration: none;
          color: purple;
          border-radius: 3px;
      }

      .pagination .active a {
          background: linear-gradient(purple, violet, purple);
          border: 1px solid black;
          color: #fff;
      }

      .container {
          display: grid;
          grid-template-columns:70vh 70vh;
      }

      .clearfix {
          margin: 20px;
          border: 1px solid;
          border-color: #371F41;
          background-color: none;
      }


      .image {
          display: flex;
          width: 20vh;
          height: 43vh;
          margin: 5px;
      }

      h3 {
          border: none;
          background-color: #a78bbb;
          text-align: center;
          font-family: arial, sans-serif;

      }

      .create-post {
          border: none;
          background-color: #a78bbb;
          font-family: arial, sans-serif;
      }

      .user_disaster {
          display: grid;
          grid-template-columns: 300px 280px;
      }

      h7 {
          border: none;
          text-align: center;
          font-family: arial, sans-serif;

      }

      h5 {
          margin-left: 20px;
          font-family: Ravier;
          color: #825991;
      }

      .content {
          font-family: arial, sans-serif;
          text-align: justify;
          margin: 10px;
      }

      .address {
          font-family: arial, sans-serif;
          text-align: justify;
          margin: 10px;
      }

      .btn {
          border: 1px solid;
          background-color: #825991;
          color: white;
      }

      .buttons {
          display: flex;
          justify-content: right;
          align-items: center;
      }

      .hot {
          color: red;
      }

      h1 {
          color: #371F41;
          text-align: center;
      }

      .container1 {
          display: grid;
          width: 70vh;
          height: 85vh;
      }

      .container2 {
          display: grid;
          width: 70vh;
          height: 40vh;
      }

      .container3 {
          display: grid;
          width: 100vh;
          height: 105vh;
      }

      .comments {
          margin: 20px;
          border: 1px solid;
          border-color: #371F41;
          background-color: none;
      }

      .container-comments {
          align-items: center;
          justify-content: center;
          display: grid;
          grid-template-columns:40vh 8vh 8vh 4vh;
      }

      .btn-edit {
          width: 70px;
          height: 37px;
      }

      .btn-home {
          width: 70px;
          height: 37px;
      }

      .btn-add-com {
          width: 140px;
          height: 37px;
      }

      .btn-success {
          width: 150px;
          height: 37px;
      }

      .btn-danger {
          width: 70px;
          height: 37px;
      }

      .comments-border {
          margin: 20px;
          border: 1px solid;
          border-color: #371F41;
          background-color: none;
      }

      .created_at {
          font-family: comics Font;
          text-align: right;
          font-style: italic;
      }

      .add-comment {
          text-align: center;
          margin: 20px;
      }

      .post-container {
          align-items: center;
          justify-content: center;
          display: grid;
          grid-template-columns:20vh 17vh 8vh;
      }

      .form1 {
          text-align: center;
          margin: 50px;
      }

      .submit {
          text-align: right;
          margin-right: 50px;
      }

      .submit1 {
          text-align: right;
          margin-right: 30px;
          margin-top: 10px;
          margin-bottom: 10px;
      }

      .back1 {
          text-align: left;
      }

      .btn-warning-edit {
          background-color: blue;
      }

      .btn-danger-edit {
          background-color: red;
      }

      .add-post {
          text-align: center;
          background-color: #9F149F;
      }

      .btn-success1 {
          background-color: #a78bbb;
      }

      .container4 {
          display: grid;
          width: 70vh;
          height: 50vh;
      }

      .container5 {
          display: grid;
          width: 40vh;
          height: 40vh;
      }

      .container6 {
          display: grid;
          width: 40vh;
          height: 33vh;
      }


      .body {
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
      }

      .form2 {
          text-align: left;
          margin: 20px;
          justify-items: left;
      }

      .label {
          font-family: script;
          font-size: 1.3em;
          color: #6d008a;
      }

      .posts {
          border: 1px solid;
          border-color: #371F41;
      }

      .box {
          display: grid;
          grid-template-columns:40vh 10vh;
          background-color: #e8c8ff;

      }

      .letterU {
          margin-top: 7px;
          color: #5f0069;
      }

      .letterC {
          font-family: broadway;
          margin-left: 5px;
      }
  </style>

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand"><span style="color: red;">Disaster</span><span style="color: #371F41;">Info</span>rmation</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link #{'active' if action_name == 'index' }", 'aria-current': 'page' %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Post', user_posts_path, class: "nav-link #{'active' if action_name == 'posts' }", 'aria-current': 'page' if user_signed_in? %>
        </li>
        <li class="nav-item">
          <%= link_to 'My Comment', user_comments_path, class: "nav-link #{'active' if action_name == 'posts' }", 'aria-current': 'page' if user_signed_in? %>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to 'Sign Out', destroy_user_session_path, data: { 'turbo-method': :delete }, class: "nav-link #{'active' if action_name == 'sign in' }", 'aria-current': 'page' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link #{'active' if action_name == 'sign in' }", 'aria-current': 'page' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<% if flash[:notice] %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if flash[:alert] %>
  <p class="alert"><%= alert %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="body">
  <%= form_with model: post do |form| %>
    <% if post.errors.any? %>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="container4">
      <%= hidden_field_tag 'from_my_post' %>
      <div class="posts">
        <div class="form2">
          <div class="label"><%= form.label :title %></div>
          <div class="text-field"><%= form.text_field :title, style: 'width: 600px;' %></div>
        </div>
        <div class="form2">
          <div class="label"><%= form.label :content %></div>
          <div class="text-field"><%= form.text_area :content, style: 'width: 600px; height: 300px' %></div>
        </div>
        <div class="form2">
          <div class="label"><%= form.label :address %></div>
          <div class="text-field"><%= form.text_field :address, style: 'width: 600px;' %></div>
        </div>
        <div class="form2">
          <div class="label"><%= form.label :type_of_disaster %></div>
          <%= form.collection_check_boxes :disaster_ids, Disaster.all, :id, :name, { inline: true } %>
        </div>
        <div class="form2">
          <div class="label"><%= form.file_field :image %></div>
        </div>
        <div class="submit">
          <%= form.submit style: 'width:100px; height:35px;' %>
          <%= link_to 'Cancel', root_path, class: 'btn' %>
        </div>
      </div>
  <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h3 class="create-post">Edit Post</h3>
<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/new.html.erb
<h3 class="create-post">Create New Post</h3>
<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/show.html.erb
<div class="container1">
  <div class="clearfix">
    <h3><%= @post.title %></h3>

    <div class="user_disaster">
      <h5><%= @post.disasters.pluck(:name).join(',') %></h5>
      <h7>By:<%= @post.user&.email %></h7>
    </div>
    <div class="image"><%= image_tag @post.image.url if @post.image.present? %></div>
    <div class="content"><p><%= @post.content %></p></div>
    <div class="address"><p><%= @post.address %></p></div>
    <p>
    </p>
  </div>
  <div class="comments">
    <h3>Comments <span style="color: white;"><%= @post.comments_count %></span></h3>
    <% @post.comments.each do |comment| %>
      <div class="comments-border">
        <div class="container-comments">
          <div class="comments1"><%= comment.content %>
            <span style="color: #825991;"> by </span><span style="color: #371f41;"><%= comment.user&.email %></span>
          </div>

          <%= link_to 'Edit', edit_post_comment_path(@post), class: 'btn btn-edit' if user_signed_in? && comment.user == current_user %>
          <%= button_to 'Delete', post_comment_path(comment.post, comment), method: :delete, class: 'btn' if user_signed_in? && comment.user == current_user %>
        </div>
        <div class="created_at">Created at: <%= comment.created_at %></div>
      </div>
    <% end %>
    <div class="add-comment"><%= link_to 'Add Comment', new_post_comment_path(@post), class: 'btn' %></div>
  </div>
  <div class="post-container">
    <%= link_to 'Back Home', root_path, class: 'btn btn-home', style: 'width:150px;' %>
    <%= link_to 'Add New Post', new_post_path, class: 'btn btn-success' %>
    <%= button_to 'Delete', post_path(@post), method: :delete, class: 'btn btn-danger' if user_signed_in? && @post.user == current_user %>
  </div>
</div>

app/views/user/comments/index.html.erb
<div class="container3">
  <div class="comments">
    <h3>Your <span style="color: #e8c8ff;">Comments </span></h3>
    <% @comments.each do |comment| %>
      <% if user_signed_in? && comment.user == current_user %>
        <div class="comments-border">
          <div class="box">
            <div class="letterC"><h4><%= comment.post.title %></h4></div>
            <div class="letterU"><h6>by:<%= comment.post.user&.email %></h6></div>
          </div>
          <div class="container-comments">
            <div class="comments1"><%= comment.content %>
              <span style="color: #825991;"> by </span><span style="color: #371f41;"><%= comment.user&.email %></span>
            </div>
            <%= link_to 'Edit', edit_post_comment_path(comment.post, comment), class: 'btn btn-edit' %>
            <%= button_to 'Delete', post_comment_path(comment.post, comment), method: :delete, class: 'btn' %>
            <div class="add-comment"><%= link_to 'Add Comment', new_post_comment_path(comment.post, comment), class: 'btn btn-add-com' %></div>
          </div>
          <div class="created_at">Created at: <%= comment.created_at %></div>
        </div>
      <% end %>
    <% end %>
    <div class="post-container">
      <%= link_to 'Back Home', root_path, class: 'btn btn-home', style: 'width:150px;' %>
      <%= link_to 'Add New Post', new_post_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

<div class="paginate"><%= paginate @comments %></div>

app/views/user/posts/index.html.erb
<h1>Your Posts</h1>
<div class="add-post"><%= link_to 'Add New Post', new_post_path, class: 'btn btn-success1' %></div>
<div class="container">
  <% @posts.each do |post| %>
    <% if user_signed_in? && post.user == current_user %>
      <div class="clearfix ">
        <h3><%= post.title %></h3>

        <div class="user_disaster">
          <h5><%= post.disasters.pluck(:name).join(',') %></h5>
          <h7>By:<%= post.user&.email %></h7>
        </div>
        <div class="image"><%= image_tag post.image.url if post.image.present? %></div>
        <div class="content"><p><%= post.content %></p></div>
        <div class="address"><p><%= post.address %></p></div>
        <p>
        <div class="buttons">
          <%= link_to 'Show', post_path(post), class: 'btn' %>
          <%= link_to 'Comments ' "#{post.comments_count}", post_comments_path(post), class: 'btn' %>
          <%= link_to 'Add Comment', new_post_comment_path(post), class: 'btn' %>
          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning-edit' %>
          <%= button_to 'Delete', post_path(post), method: :delete, class: 'btn btn-danger-edit' %>
        </div>
        </p>
      </div>
    <% end %>
  <% end %>
</div>
<div class="paginate"><%= paginate @posts %></div>

app/views/welcome/index.html.erb
<h1>Welcome to DisasterInformation!</h1>
<div class="container">
  <% @posts.each do |post| %>
    <div class="clearfix ">
      <h3><%= post.title %></h3>

      <div class="user_disaster">
        <h5><%= post.disasters.pluck(:name).join(',') %></h5>
        <h7>By:<%= post.user&.email %></h7>
      </div>
      <div class="image"><%= image_tag post.image.url if post.image.present? %></div>
      <div class="content"><p><%= post.content %></p></div>
      <div class="address"><p><%= post.address %></p></div>
      <p>
      <div class="buttons">
        <%= link_to 'Show', post_path(post), class: 'btn' %>
        <%= link_to 'Comments ' "#{post.comments_count}", post_comments_path(post), class: 'btn' %>
        <%= link_to 'Add Comment', new_post_comment_path(post), class: 'btn' %>
        <div class="hot">
          <% if @top_posts.include?(post) %>
            <span class="hot-tag">HOT</span>
          <% end %>
        </div>
      </div>
      </p>
    </div>
  <% end %>
</div>
<div class="paginate"><%= paginate @posts %></div>